spring:
  application:
    name: zuul
server:
  port : 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    appname: zuul
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}

zuul:
  routes:
    offer:
      path: /offer/**
      url: http://localhost:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://shoe:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://wishlist:1003
    cart:
      path: /cart/**
      url: http://cart:1004/api/v1
    shoe-service:
      path: /shoeapi/**
      serviceId: shoe
    offer-service:
      path: /offerapi/**
      serviceId: offers-client
    cart-service:
      path: /cartapi/**
      serviceId: cart-client